version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "DNDdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "logging_collector=off"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_duration=on"
      - "-c"
      - "log_min_duration_statement=0"
volumes:
  postgres-data: